fullstack-e2e:
  name: Fullstack E2E (Cypress)
  needs: [frontend-build, backend-package]
  if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true' }}
  runs-on: ubuntu-latest
  timeout-minutes: 25
  steps:
    - uses: actions/checkout@v4

    - name: Download FE build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/build
      continue-on-error: true

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm
        cache-dependency-path: frontend/package-lock.json
    - name: Install FE deps
      working-directory: frontend
      run: npm ci

    - name: Cache Cypress
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: cypress-${{ runner.os }}-

    - name: Serve FE build if exists
      id: servefe
      working-directory: frontend
      run: |
        if [ -d build ]; then
          npx http-server ./build -p 3000 --silent &
          echo "FE_URL=http://localhost:3000" >> "$GITHUB_ENV"
          echo "served=true" >> "$GITHUB_OUTPUT"
        else
          echo "served=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Wait FE
      if: ${{ steps.servefe.outputs.served == 'true' }}
      run: npx wait-on http://localhost:3000 --timeout 120000

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven

    # ✅ Start backend และ log output
    - name: Run BE (spring-boot:run, profile=test)
      working-directory: backend
      env:
        SPRING_PROFILES_ACTIVE: test
      run: |
        ./mvnw -q -DskipTests spring-boot:run > backend.log 2>&1 &
        echo "API_URL=http://localhost:8080" >> "$GITHUB_ENV"
        echo "Backend starting..."
        sleep 10
        tail -n 20 backend.log || true

    # ✅ Wait BE (รอ 4 นาที + retry)
    - name: Wait BE
      run: |
        echo "Waiting for backend on port 8080 ..."
        npx wait-on tcp:localhost:8080 --timeout 240000 || (
          echo "Backend did not start in time. Printing last logs:" && \
          tail -n 40 backend/backend.log && exit 1
        )

    - name: Run Cypress
      uses: cypress-io/github-action@v6
      with:
        working-directory: frontend
        install: false
        browser: electron
        headless: true
        config: video=false
      env:
        CI: true
        CYPRESS_baseUrl: ${{ env.FE_URL }}
        CYPRESS_API_URL: ${{ env.API_URL }}

    - name: Upload screenshots (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fullstack-screenshots
        path: frontend/cypress/screenshots/**
        if-no-files-found: ignore
