name: Financial App CI (Build & Test)

on:
  push:
    branches: [ testy ]
  pull_request:
    branches: [ testy ]
  workflow_dispatch:

concurrency:
  group: financial-app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # เช็กว่าแก้ฝั่งไหนบ้าง เพื่อรันเฉพาะที่จำเป็น
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - '.github/workflows/**'
            backend:
              - 'backend/**'
              - '.github/workflows/**'

  # ===== FRONTEND =====
  frontend-check:
    name: Frontend Lint & TypeCheck
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      # ทำให้ไฟล์นี้เป็น no-op ใน CI เพื่อเลี่ยง dependency web-vitals
      - name: Disable reportWebVitals for CI
        working-directory: frontend
        run: |
          cat > src/reportWebVitals.ts <<'EOF'
          const reportWebVitals = () => {};
          export default reportWebVitals;
          EOF

      - name: Lint
        working-directory: frontend
        run: |
          if ls .eslintrc* >/dev/null 2>&1; then
            npx eslint . --max-warnings=0
          else
            echo "No ESLint config found; skip lint."
          fi

      - name: Type check
        working-directory: frontend
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc --noEmit --skipLibCheck
          else
            echo "No tsconfig.json found; skip type check."
          fi

      - name: Build (sanity check)
        working-directory: frontend
        run: npm run build --if-present

  # ===== BACKEND =====
  backend-test:
    name: Backend Unit Test
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x ./mvnw

      - name: Run Unit Tests
        working-directory: backend
        run: ./mvnw -q test
