name: Financial App CI (Frontend build + Backend package)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: financial-app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend-build:
    name: Frontend Build (no tests)
    needs: changes
    # PR/dispatch รันทันที, push จะรันเมื่อมีไฟล์ใน frontend/** เปลี่ยน
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build (if present)
        working-directory: frontend
        run: npm run build --if-present

      - name: Upload build artifact (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ github.run_id }}
          path: frontend/build
          if-no-files-found: ignore

  backend:
    name: Backend Build (with tests)
    needs: changes
    # PR/dispatch รันทันที, push จะรันเมื่อมีไฟล์ใน backend/** เปลี่ยน
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: backend/pom.xml

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x ./mvnw

      # package จะรัน tests โดยอัตโนมัติ (ไม่ skip)
      - name: Build & Test
        working-directory: backend
        run: ./mvnw -q package

      - name: Upload backend artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts-${{ github.run_id }}
          path: |
            backend/target/*.jar
            backend/target/surefire-reports/**
          if-no-files-found: warn