# Run BE (spring-boot:run, profile=test)
- name: Run BE (spring-boot:run, profile=test)
  working-directory: backend
  env:
    SPRING_PROFILES_ACTIVE: test
  run: |
    chmod +x ./mvnw
    ./mvnw -q -DskipTests spring-boot:run > backend.log 2>&1 &
    echo "API_URL=http://localhost:8081" >> "$GITHUB_ENV"   # 👈 เปลี่ยนเป็น 8081
    sleep 10
    tail -n 20 backend.log || true

# Run Cypress
- name: Run Cypress
  uses: cypress-io/github-action@v6
  with:
    working-directory: frontend
    install: false
    browser: electron
    quiet: true
    config: video=false
    wait-on: 'http://localhost:3000,tcp:localhost:8081'     # 👈 เปลี่ยนเป็น 8081
    wait-on-timeout: 240
  env:
    CI: true
    CYPRESS_baseUrl: ${{ env.FE_URL }}
    CYPRESS_API_URL: ${{ env.API_URL }}                     # จะกลายเป็น http://localhost:8081
