name: Financial App CI (Frontend + Backend build only)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: financial-app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ยังเก็บไว้ได้ เผื่ออนาคตอยากใช้ผล filter
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  frontend-build:
    name: Frontend Build (no tests)
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        working-directory: frontend
        run: npm ci
      - name: Build (if present)
        working-directory: frontend
        run: npm run build --if-present
      - name: Upload build artifact (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
          if-no-files-found: ignore

  backend-build:
    name: Backend Build (no tests)
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x ./mvnw
      - name: Build (compile/package fast)
        working-directory: backend
        run: ./mvnw -B -ntp -DskipTests -Dspring-boot.repackage.skip=true clean package
      - name: Upload backend artifact (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            backend/target/*.jar
            backend/target/*.war
          if-no-files-found: ignore
