name: Financial App CI Pipeline

on:
  push:
    branches: [ testy ]
  pull_request:
    branches: [ testy ]
  workflow_dispatch:

concurrency:
  group: financial-app-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect Code Changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend:  ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'package.json'
              - 'package-lock.json'
              - 'src/**'
              - 'public/**'
              - '.github/workflows/**'
            backend:
              - 'backend/**'
              - '.github/workflows/**'

  frontend-lint:
    name: Frontend Lint & Type Check
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          npm ci || npm install
      - name: Run Lint
        run: |
          npm run lint --if-present || echo "No lint script found, skipping."
      - name: Run Type Check
        run: |
          npm run type-check --if-present || echo "No type-check script found, skipping."

  backend-lint:
    name: Backend Static Analysis
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Checkstyle
        run: |
          cd backend
          ./mvnw -B -q -DskipTests=true checkstyle:checkstyle || echo "Checkstyle skipped."

  frontend-build:
    name: Frontend Build
    needs: frontend-lint
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install & Build
        run: |
          npm ci || npm install
          if npm list react-scripts >/dev/null 2>&1; then
            npm run build
          else
            echo "react-scripts not found, skipping build."
          fi

  backend-build:
    name: Backend Compile
    needs: backend-lint
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Fix mvnw permission
        run: |
          cd backend
          chmod +x mvnw || true
          sed -i 's/\r$//' mvnw || true
      - name: Compile Backend
        run: |
          cd backend
          ./mvnw -B -DskipTests=true compile || mvn -B -DskipTests=true compile

  frontend-test:
    name: Frontend Unit Tests
    needs: frontend-build
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Frontend Tests
        run: |
          npm ci || npm install
          npm test --yes || npm run test --if-present || echo "No frontend tests found, skipping."

  backend-test:
    name: Backend Test Suite
    needs: backend-build
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Backend Tests
        run: |
          cd backend
          chmod +x mvnw || true
          ./mvnw -B test || mvn -B test
